- hosts: all
  become: yes
  become_user: root
  roles:
    - role: rvm.ruby
      tags: ruby
      rvm1_rubies: ['ruby-2.5.1']
      rvm1_install_flags: '--auto-dotfiles --user-install'
      rvm1_user: vagrant
      rvm1_bundler_install: True
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest 
    - name: centos release
      yum:
        name: centos-release-scl
        state: latest
    - name: git
      yum:
        name: git
        state: latest
    - name: epel-release
      yum:
        name: epel-release
        state: latest
    - name: rubygems
      yum:
        name: rubygems
        state: latest 
    - name: ImageMagick
      yum:
        name: ImageMagick
        state: latest
    - name: dos2unix
      yum:
        name: dos2unix
        state: latest
    - name: pip
      yum:
        name: python-pip
        state: latest
    - name: pip install
      easy_install:
        name: pip
        state: latest
    - name: Flask
      pip:
        name: Flask
        state: latest
    - name: flask_cors
      pip:
        name: flask_cors
        state: latest
        
